services:

  flask_app:
    container_name: flask_app
    image: flask:1.0
    build: .
    ports:
      - 5000:5000

  flaskdb:
    image: postgres
    container_name: flaskdb
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres





